apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app1: ashudep1
  name: ashudep1 # name of deployment 
  namespace: ashu-space 
spec:
  replicas: 1 # no of pod 
  selector:
    matchLabels:
      app: ashudep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashudep1
    spec:
      volumes: # IS for creating volume 
      - name: ashuvol1 # name of volume 
        emptyDir: {}  
      containers:
      - image: dockerashu/ows:v002
        name: ows
        env: # a speicfig app  
        - name: x
          value: app2 
        resources: {}
status: {}
