apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod1
  name: mypod1
spec:
  imagePullSecrets: # to call secret in your namespace
  - name: ashusec   # name of secret 
  containers:
  - command:
    - ping
    - fb.com
    image: phx.ocir.io/axmbtg8judkl/alpine:v1
    name: mypod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
