apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # label of pod 
    run: ashupod3  # run is a key and ashupod3 is value 
  name: ashupod3  # name of the POD
spec:
  containers:
  - image: nginx
    name: ashupod3
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
